version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finance_api_db
    restart: always
    environment:
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=finance_password
      - POSTGRES_DB=finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
